server:
    port: 8999

mongodb:
    host: 192.168.22.4
    port: 37017
    database: grooo-market
    username: market
    password: s59PFm)u4WNHrZge

logging:
    level:
        root: INFO

config:
    # Tính lại theo ngày và mã
    start-date: 2022-07-25 00:00:00
    end-date: 2022-07-29 23:59:59
    symbols: A32,AAA
    # Tính lại tất cả
#    start-date:
#    end-date:
#    symbols: